# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # test against latest update of each major Java version:
        java: [ 1.8, 12, 13, 14 ]
    name: Test on Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup java ${{ matrix.java }}
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Test with Maven
      run: mvn test --file pom.xml
